export const PHONE_COUNTRIES = [
    ['AF', 'Afganistán', '93'],
    ['AL', 'Albania', '355'],
    ['DE', 'Alemania', '49'],
    ['AD', 'Andorra', '376'],
    ['AO', 'Angola', '244'],
    ['SA', 'Arabia Saudita', '966'],
    ['DZ', 'Argelia', '213'],
    ['AR', 'Argentina', '54'],
    ['AM', 'Armenia', '374'],
    ['AU', 'Australia', '61'],
    ['AT', 'Austria', '43'],
    ['AZ', 'Azerbaiyán', '994'],
    ['BE', 'Bélgica', '32'],
    ['BO', 'Bolivia', '591'],
    ['BA', 'Bosnia y Herzegovina', '387'],
    ['BR', 'Brasil', '55'],
    ['BG', 'Bulgaria', '359'],
    ['CV', 'Cabo Verde', '238'],
    ['KH', 'Camboya', '855'],
    ['CM', 'Camerún', '237'],
    ['CA', 'Canadá', '1'],
    ['QA', 'Catar', '974'],
    ['CL', 'Chile', '56'],
    ['CN', 'China', '86'],
    ['CY', 'Chipre', '357'],
    ['CO', 'Colombia', '57'],
    ['KR', 'Corea del Sur', '82'],
    ['CR', 'Costa Rica', '506'],
    ['HR', 'Croacia', '385'],
    ['CU', 'Cuba', '53'],
    ['DK', 'Dinamarca', '45'],
    ['EC', 'Ecuador', '593'],
    ['EG', 'Egipto', '20'],
    ['SV', 'El Salvador', '503'],
    ['AE', 'Emiratos Árabes Unidos', '971'],
    ['SK', 'Eslovaquia', '421'],
    ['SI', 'Eslovenia', '386'],
    ['ES', 'España', '34'],
    ['US', 'Estados Unidos', '1'],
    ['EE', 'Estonia', '372'],
    ['PH', 'Filipinas', '63'],
    ['FI', 'Finlandia', '358'],
    ['FR', 'Francia', '33'],
    ['GE', 'Georgia', '995'],
    ['GH', 'Ghana', '233'],
    ['GR', 'Grecia', '30'],
    ['GT', 'Guatemala', '502'],
    ['GN', 'Guinea', '224'],
    ['GQ', 'Guinea Ecuatorial', '240'],
    ['HT', 'Haití', '509'],
    ['HN', 'Honduras', '504'],
    ['HK', 'Hong Kong', '852'],
    ['HU', 'Hungría', '36'],
    ['IN', 'India', '91'],
    ['ID', 'Indonesia', '62'],
    ['IQ', 'Irak', '964'],
    ['IR', 'Irán', '98'],
    ['IE', 'Irlanda', '353'],
    ['IS', 'Islandia', '354'],
    ['IL', 'Israel', '972'],
    ['IT', 'Italia', '39'],
    ['JP', 'Japón', '81'],
    ['JO', 'Jordania', '962'],
    ['KZ', 'Kazajistán', '7'],
    ['KE', 'Kenia', '254'],
    ['KW', 'Kuwait', '965'],
    ['LV', 'Letonia', '371'],
    ['LB', 'Líbano', '961'],
    ['LY', 'Libia', '218'],
    ['LI', 'Liechtenstein', '423'],
    ['LT', 'Lituania', '370'],
    ['LU', 'Luxemburgo', '352'],
    ['MO', 'Macao', '853'],
    ['MK', 'Macedonia del Norte', '389'],
    ['MG', 'Madagascar', '261'],
    ['MY', 'Malasia', '60'],
    ['MT', 'Malta', '356'],
    ['MA', 'Marruecos', '212'],
    ['MU', 'Mauricio', '230'],
    ['MX', 'México', '52'],
    ['MD', 'Moldavia', '373'],
    ['MC', 'Mónaco', '377'],
    ['MN', 'Mongolia', '976'],
    ['ME', 'Montenegro', '382'],
    ['MZ', 'Mozambique', '258'],
    ['NO', 'Noruega', '47'],
    ['NZ', 'Nueva Zelanda', '64'],
    ['NL', 'Países Bajos', '31'],
    ['PK', 'Pakistán', '92'],
    ['PA', 'Panamá', '507'],
    ['PY', 'Paraguay', '595'],
    ['PE', 'Perú', '51'],
    ['PL', 'Polonia', '48'],
    ['PT', 'Portugal', '351'],
    ['GB', 'Reino Unido', '44'],
    ['CZ', 'República Checa', '420'],
    ['DO', 'República Dominicana', '1'],
    ['RO', 'Rumanía', '40'],
    ['RU', 'Rusia', '7'],
    ['SN', 'Senegal', '221'],
    ['RS', 'Serbia', '381'],
    ['SG', 'Singapur', '65'],
    ['SY', 'Siria', '963'],
    ['ZA', 'Sudáfrica', '27'],
    ['SE', 'Suecia', '46'],
    ['CH', 'Suiza', '41'],
    ['TH', 'Tailandia', '66'],
    ['TW', 'Taiwán', '886'],
    ['TZ', 'Tanzania', '255'],
    ['TN', 'Túnez', '216'],
    ['TR', 'Turquía', '90'],
    ['UA', 'Ucrania', '380'],
    ['UG', 'Uganda', '256'],
    ['UY', 'Uruguay', '598'],
    ['VE', 'Venezuela', '58'],
    ['VN', 'Vietnam', '84'],
].map(([iso, name, dial]) => ({ iso, name, dial }));

export function findPhoneCountry(iso) {
    return (
        PHONE_COUNTRIES.find((country) => country.iso === iso) ||
        PHONE_COUNTRIES.find((country) => country.iso === 'ES')
    );
}

export function flagUrl(iso, width = 40) {
    return `https://flagcdn.com/w${width}/${String(iso).toLowerCase()}.png`;
}
